name: Code Inspector

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'

jobs:
  code-inspection:
    name: Code Inspection
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip install flake8
          pip install pylint

      - name: Run Flake8
        id: flake8
        run: |
          flake8 . > flake8_results.txt || true

      - name: Run Pylint
        id: pylint
        run: |
          pylint . > pylint_results.txt || true

      - name: Parse Flake8 output and calculate score
        run: |
          flake8_issues=0
          if grep -q '^[^:]*:.*:' flake8_results.txt; then
            flake8_issues=$(grep -c '^[^:]*:.*:' flake8_results.txt)
          fi
          flake8_score=$((100 - flake8_issues * 10))
          echo "Flake8 score: $flake8_score"
          if [ $flake8_score -lt 100 ]; then
            echo "Code quality score: FAIL"
            exit 1
          else
            echo "Code quality score: PASS"
          fi


      - name: Display Flake8 issues
        if: always()
        run: |
          echo "Flake8 issues found:"
          cat flake8_results.txt
