name: Code Inspector

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'

jobs:
  code-inspection:
    name: Code Inspection
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip install flake8
          pip install pylint

      - name: Run Flake8
        id: flake8
        run: flake8 . || true

      - name: Run Pylint
        id: pylint
        run: |
          pylint . || true

      - name: Display Code Quality Score
        run: |
          flake8_score=$(echo "${{ steps.flake8.outputs.stdout }}" | grep -c '^')
          pylint_score=$(echo "${{ steps.pylint.outputs.stdout }}" | grep -c 'Your code has been rated at')
          total_score=$((flake8_score + pylint_score))
          echo "Code quality score: $total_score"
          if [ "$total_score" -gt 0 ]; then
            echo "Errors found in the code."
          else
            echo "No errors found in the code."
          fi
